Accounts:
    FrontEndUsers:
      roleClass: App\Controller\UserAccounts\UserController
      actions: ["view","add","edit","delete","info","approve","decline"]
      key: users-accounts

    Roles:
      roleClass: App\Controller\UserAccounts\RoleController
      actions: ["view","add","edit","delete"]
      key: role-configuration


Configuration:
    ContentType:
      roleClass: App\Controller\Configuration\ContentTypeController
      actions: [ "view","add","edit","delete" ]
      key: content-type-configuration